<?php

/*
|--------------------------------------------------------------------------
| Model Factories
|--------------------------------------------------------------------------
|
| Here you may define all of your model factories. Model factories give
| you a convenient way to create models for testing and seeding your
| database. Just tell the factory how a default model should look.
|
*/

$factory->define(App\User::class, function (Faker\Generator $faker) {
    return [
        'first_name'    => $faker->firstName(),
        'last_name'     => $faker->lastName(),
        'email'         => $faker->email(),
        'password'      => bcrypt('pleksi')
    ];
});

$factory->define(App\Image::class, function (Faker\Generator $faker) {

    $year   = date('Y');
    $month  = date('m');
    $day    = date('d');
    $rnd    = $faker->numberBetween(0, 1);
    $id     = md5(uniqid(rand(), true));

    return [
        'id'            => $id,
        'path'          => sprintf('/media/%s/%s/%s/%s.%s', $year, $month, $day, $id, ['jpg', 'png'][$rnd]),
        'mime'          => ['image/jpeg', 'image/png'][$rnd],
        'extension'     => ['jpg', 'png'][$rnd]
    ];
});

$factory->define(App\Car::class, function (Faker\Generator $faker) {

    $brandsAndModels = [
      'Alfa Romeo|33',
      'Alfa Romeo|75',
      'Alfa Romeo|90',
      'Alfa Romeo|145',
      'Alfa Romeo|146',
      'Alfa Romeo|147',
      'Alfa Romeo|155',
      'Alfa Romeo|156',
      'Alfa Romeo|159',
      'Alfa Romeo|164',
      'Alfa Romeo|166',
      'Alfa Romeo|4C',
      'Alfa Romeo|8C',
      'Alfa Romeo|1750',
      'Alfa Romeo|Alfasud',
      'Alfa Romeo|Alfetta',
      'Alfa Romeo|Brera',
      'Alfa Romeo|Crosswagon',
      'Alfa Romeo|Giulia',
      'Alfa Romeo|Giulietta',
      'Alfa Romeo|GT',
      'Alfa Romeo|GTV',
      'Alfa Romeo|MiTo',
      'Alfa Romeo|RZ',
      'Alfa Romeo|SZ',
      'Alfa Romeo|Spider',
      'Alfa Romeo|Sprint',
      'Alfa Romeo|Stelvio',
      'Aston Martin|Cygnet',
      'Aston Martin|DB',
      'Aston Martin|DB7',
      'Aston Martin|DB9',
      'Aston Martin|DB11',
      'Aston Martin|DBS',
      'Aston Martin|Lagonda',
      'Aston Martin|One-77',
      'Aston Martin|Rapide',
      'Aston Martin|V8',
      'Aston Martin|Vantage',
      'Aston Martin|Vanquish',
      'Aston Martin|Virage',
      'Aston Martin|Volante',
      'Aston Martin|Zagato',
      'Audi|50',
      'Audi|60',
      'Audi|80',
      'Audi|90',
      'Audi|100',
      'Audi|200',
      'Audi|A1',
      'Audi|A2',
      'Audi|A3',
      'Audi|A4',
      'Audi|A5',
      'Audi|A6',
      'Audi|A7',
      'Audi|A8',
      'Audi|Allroad',
      'Audi|Coupe',
      'Audi|Cabriolet',
      'Audi|Q1',
      'Audi|Q2',
      'Audi|Q3',
      'Audi|Q5',
      'Audi|Q7',
      'Audi|R8',
      'Audi|RS2',
      'Audi|RS3',
      'Audi|RS4',
      'Audi|RS5',
      'Audi|RS6',
      'Audi|RS7',
      'Audi|RS Q3',
      'Audi|S1',
      'Audi|S2',
      'Audi|S3',
      'Audi|S4',
      'Audi|S5',
      'Audi|S6',
      'Audi|S7',
      'Audi|S8',
      'Audi|SQ5',
      'Audi|SQ7',
      'Audi|TT',
      'Audi|V8',
      'Austin|Metro',
      'Austin|Mini',
      'Autobianchi|A112',
      'Autobianchi|Bianchina',
      'Autobianchi|Primula',
      'Bentley|Arnage',
      'Bentley|Azure',
      'Bentley|Bentayga',
      'Bentley|Brooklands',
      'Bentley|Continental',
      'Bentley|Eight',
      'Bentley|Mulsanne',
      'Bentley|Turbo',
      'BMW|1802',
      'BMW|2002',
      'BMW|i3',
      'BMW|i8',
      'BMW|M1',
      'BMW|M2',
      'BMW|M3',
      'BMW|M4',
      'BMW|M5',
      'BMW|M6',
      'BMW|Serija 1',
      'BMW|Serija 2',
      'BMW|Serija 3',
      'BMW|Serija 4',
      'BMW|Serija 5',
      'BMW|Serija 6',
      'BMW|Serija 7',
      'BMW|Serija 8',
      'BMW|Serija X1',
      'BMW|Serija X3',
      'BMW|Serija X4',
      'BMW|Serija X5',
      'BMW|Serija X6',
      'BMW|Z1',
      'BMW|Z3',
      'BMW|Z4',
      'BMW|Z8',
      'Bugatti|EB 110',
      'Bugatti|Veyron',
      'Bugatti|Chiron',
      'Cadillac|Allante',
      'Cadillac|BLS',
      'Cadillac|DeVille',
      'Cadillac|CTS',
      'Cadillac|Eldorado',
      'Cadillac|Escalade',
      'Cadillac|Fleetwood',
      'Cadillac|Seville',
      'Cadillac|SRX',
      'Cadillac|STS',
      'Cadillac|XLR',
      'Chevrolet|Astro',
      'Chevrolet|Avalanche',
      'Chevrolet|Aveo',
      'Chevrolet|Beretta',
      'Chevrolet|Blazer',
      'Chevrolet|Camaro',
      'Chevrolet|Captiva',
      'Chevrolet|Cavalier',
      'Chevrolet|Corvette',
      'Chevrolet|Cruze',
      'Chevrolet|Epica',
      'Chevrolet|Evanda',
      'Chevrolet|HHR',
      'Chevrolet|Kalos',
      'Chevrolet|Lacetti',
      'Chevrolet|Lumina',
      'Chevrolet|Malibu',
      'Chevrolet|Matiz',
      'Chevrolet|Nubira',
      'Chevrolet|Orlando',
      'Chevrolet|Rezzo',
      'Chevrolet|Spark',
      'Chevrolet|Suburban',
      'Chevrolet|Tacuma',
      'Chevrolet|Tahoe',
      'Chevrolet|TrailBlazer',
      'Chevrolet|Trans Sport',
      'Chevrolet|Trax',
      'Chevrolet|Volt',
      'Chrysler|300 C',
      'Chrysler|300 M',
      'Chrysler|Crossfire',
      'Chrysler|ES',
      'Chrysler|Le Baron',
      'Chrysler|Neon',
      'Chrysler|New Yorker',
      'Chrysler|Pacifica',
      'Chrysler|PT Cruiser',
      'Chrysler|Saratoga',
      'Chrysler|Sebring',
      'Chrysler|Stratus',
      'Chrysler|Viper',
      'Chrysler|Vision',
      'Chrysler|Voyager',
      'Chrysler|Grand Voyager',
      'Citroen|2 CV',
      'Citroen|Ami',
      'Citroen|AX',
      'Citroen|Berlingo',
      'Citroen|BX',
      'Citroen|C1',
      'Citroen|C2',
      'Citroen|C3',
      'Citroen|C3 Picasso',
      'Citroen|C3 Pluriel',
      'Citroen|C4',
      'Citroen|C4 Aircross',
      'Citroen|C4 Cactus',
      'Citroen|C4 Picasso',
      'Citroen|C4 Grand Picasso',
      'Citroen|C5',
      'Citroen|C6',
      'Citroen|C8',
      'Citroen|C-Crosser',
      'Citroen|C-Eysee',
      'Citroen|C-Zero',
      'Citroen|CX',
      'Citroen|DS',
      'Citroen|DS3',
      'Citroen|DS4',
      'Citroen|DS5',
      'Citroen|Dyane',
      'Citroen|Evasion',
      'Citroen|GS',
      'Citroen|GSA',
      'Citroen|Jumpy',
      'Citroen|LN',
      'Citroen|Nemo',
      'Citroen|Saxo',
      'Citroen|SM',
      'Citroen|SpaceTourer',
      'Citroen|Visa',
      'Citroen|Xantia',
      'Citroen|XM',
      'Citroen|Xsara',
      'Citroen|Xsara Picasso',
      'Citroen|ZX',
      'Dacia|Dokker',
      'Dacia|Lodgy',
      'Dacia|Logan',
      'Dacia|Sandero',
      'Dacia|Duster',
      'Daewoo|Chairman',
      'Daewoo|Espero',
      'Daewoo|Evanda',
      'Daewoo|Kalos',
      'Daewoo|Korando',
      'Daewoo|Lacetti',
      'Daewoo|Lanos',
      'Daewoo|Leganza',
      'Daewoo|Matiz',
      'Daewoo|Musso',
      'Daewoo|Nexia',
      'Daewoo|Nubira',
      'Daewoo|Racer',
      'Daewoo|Tacuma',
      'Daewoo|Tico',
      'Daihatsu|Applause',
      'Daihatsu|Charade',
      'Daihatsu|Copen',
      'Daihatsu|Cuore',
      'Daihatsu|Feroza',
      'Daihatsu|Freeclimber',
      'Daihatsu|Gran Move',
      'Daihatsu|Materia',
      'Daihatsu|Move',
      'Daihatsu|Rocky',
      'Daihatsu|Sirion',
      'Daihatsu|Terios',
      'Daihatsu|Trevis',
      'Daihatsu|YRV',
      'Dodge|Avenger',
      'Dodge|Caliber',
      'Dodge|Caravan',
      'Dodge|Charger',
      'Dodge|Durango',
      'Dodge|Journey',
      'Dodge|Magnum',
      'Dodge|Nitro',
      'Dodge|RAM',
      'Dodge|Stealth',
      'Dodge|Viper',
      'DS Automobiles|DS3',
      'DS Automobiles|DS4',
      'DS Automobiles|DS5',
      'Ferrari|208',
      'Ferrari|308',
      'Ferrari|328',
      'Ferrari|348',
      'Ferrari|355',
      'Ferrari|360',
      'Ferrari|400',
      'Ferrari|412',
      'Ferrari|430',
      'Ferrari|456',
      'Ferrari|458',
      'Ferrari|488',
      'Ferrari|512',
      'Ferrari|550 Maranello',
      'Ferrari|575',
      'Ferrari|599',
      'Ferrari|612 Scaglietti',
      'Ferrari|California',
      'Ferrari|Dino',
      'Ferrari|Enzo',
      'Ferrari|F12',
      'Ferrari|F40',
      'Ferrari|F50',
      'Ferrari|FF',
      'Ferrari|GTC4Lusso',
      'Ferrari|LaFerrari',
      'Ferrari|Mondial',
      'Ferrari|Superamerica',
      'Ferrari|Testarossa',
      'Fiat|1100',
      'Fiat|124',
      'Fiat|124 Spider',
      'Fiat|125',
      'Fiat|126',
      'Fiat|127',
      'Fiat|130',
      'Fiat|131',
      'Fiat|132',
      'Fiat|500',
      'Fiat|500C',
      'Fiat|500L',
      'Fiat|500X',
      'Fiat|600',
      'Fiat|850',
      'Fiat|1500',
      'Fiat|Albea',
      'Fiat|Argenta',
      'Fiat|Barchetta',
      'Fiat|Brava',
      'Fiat|Bravo',
      'Fiat|Campagnola',
      'Fiat|Cinquecento',
      'Fiat|Coupe',
      'Fiat|Croma',
      'Fiat|Doblo',
      'Fiat|Freemont',
      'Fiat|Fullback',
      'Fiat|Idea',
      'Fiat|Linea',
      'Fiat|Marea',
      'Fiat|Multipla',
      'Fiat|Palio',
      'Fiat|Panda',
      'Fiat|Punto',
      'Fiat|Qubo',
      'Fiat|Regata',
      'Fiat|Ritmo',
      'Fiat|Scudo',
      'Fiat|Sedici',
      'Fiat|Seicento',
      'Fiat|Spider',
      'Fiat|Stilo',
      'Fiat|Tempra',
      'Fiat|Tipo',
      'Fiat|Ulysse',
      'Fiat|Uno',
      'Fiat|X 1/9',
      'Fisker|Karma',
      'Ford|Aerostar',
      'Ford|Bronco',
      'Ford|B-Max',
      'Ford|C-Max',
      'Ford|Grand C-Max',
      'Ford|Capri',
      'Ford|Cougar',
      'Ford|Ecosport',
      'Ford|Edge',
      'Ford|Escort',
      'Ford|Excursion',
      'Ford|Expedition',
      'Ford|Explorer',
      'Ford|Fiesta',
      'Ford|Focus',
      'Ford|Fusion',
      'Ford|Galaxy',
      'Ford|Granada',
      'Ford|GT',
      'Ford|Ka',
      'Ford|Kuga',
      'Ford|Maverick',
      'Ford|Mondeo',
      'Ford|Mustang',
      'Ford|Orion',
      'Ford|Probe',
      'Ford|Puma',
      'Ford|Ranger',
      'Ford|S-Max',
      'Ford|Scorpio',
      'Ford|Sierra',
      'Ford|StreetKa',
      'Ford|Taunus',
      'Ford|Taurus',
      'Ford|Thunderbird',
      'Ford|Tourneo',
      'Ford|Windstar',
      'Greatwall|Hover',
      'Grecav|Sonique',
      'Honda|Accord',
      'Honda|Civic',
      'Honda|Concerto',
      'Honda|CR-V',
      'Honda|CR-Z',
      'Honda|CRX',
      'Honda|FR-V',
      'Honda|HR-V',
      'Honda|Insight',
      'Honda|Integra',
      'Honda|Jazz',
      'Honda|Legend',
      'Honda|Logo',
      'Honda|NSX',
      'Honda|Odyssey',
      'Honda|Pilot',
      'Honda|Prelude',
      'Honda|S2000',
      'Honda|Shuttle',
      'Honda|Stream',
      'Hummer|H1',
      'Hummer|H2',
      'Hummer|H3',
      'Hyundai|Accent',
      'Hyundai|Atos',
      'Hyundai|Coupe',
      'Hyundai|Elantra',
      'Hyundai|Excel',
      'Hyundai|Galloper',
      'Hyundai|Genesis',
      'Hyundai|Getz',
      'Hyundai|Grandeur',
      'Hyundai|H-1',
      'Hyundai|H100',
      'Hyundai|i10',
      'Hyundai|i20',
      'Hyundai|i30',
      'Hyundai|i40',
      'Hyundai|ix20',
      'Hyundai|ix35',
      'Hyundai|ix55',
      'Hyundai|Ioniq',
      'Hyundai|Lantra',
      'Hyundai|Matrix',
      'Hyundai|Pony',
      'Hyundai|S-Coupe',
      'Hyundai|Santa Fe',
      'Hyundai|Grand Santa Fe',
      'Hyundai|Santamo',
      'Hyundai|Sonata',
      'Hyundai|Terracan',
      'Hyundai|Trajet',
      'Hyundai|Tucson',
      'Hyundai|Veloster',
      'Hyundai|XG',
      'Infiniti|G Coupe',
      'Infiniti|G Cabrio',
      'Infiniti|G',
      'Infiniti|M',
      'Infiniti|EX',
      'Infiniti|FX',
      'Infiniti|JX',
      'Infiniti|QX',
      'Infiniti|Q50',
      'Infiniti|Q60',
      'Infiniti|Q70',
      'Infiniti|QX50',
      'Infiniti|QX60',
      'Infiniti|QX70',
      'Infiniti|QX80',
      'Isuzu|Amigo',
      'Isuzu|Campo',
      'Isuzu|D-Max',
      'Isuzu|Gemini',
      'Isuzu|Mu',
      'Isuzu|Trooper',
      'Iveco|Massif',
      'Jaguar|Daimler',
      'Jaguar|MK-II',
      'Jaguar|E-Type',
      'Jaguar|F-Pace',
      'Jaguar|F-Type',
      'Jaguar|S-Type',
      'Jaguar|X-Type',
      'Jaguar|XE',
      'Jaguar|XF',
      'Jaguar|XJ',
      'Jaguar|XJS',
      'Jaguar|XK',
      'Jeep|CJ',
      'Jeep|Cherokee',
      'Jeep|Commander',
      'Jeep|Compass',
      'Jeep|Grand Cherokee',
      'Jeep|Patriot',
      'Jeep|Renegade',
      'Jeep|Wagoneer',
      'Jeep|Willys',
      'Jeep|Wrangler',
      'Kia|Carens',
      'Kia|Carnival',
      'Kia|CeeD',
      'Kia|Cerato',
      'Kia|Clarus',
      'Kia|Elan',
      'Kia|Joice',
      'Kia|Magentis',
      'Kia|Niro',
      'Kia|Opirus',
      'Kia|Optima',
      'Kia|Picanto',
      'Kia|Pride',
      'Kia|Pro_Ceed',
      'Kia|Retona',
      'Kia|Rio',
      'Kia|Rocsta',
      'Kia|Sephia',
      'Kia|Sorento',
      'Kia|Soul',
      'Kia|Spectra',
      'Kia|Sportage',
      'Kia|Stinger',
      'Kia|Venga',
      'KTM|X-Bow',
      'Lada|110',
      'Lada|111',
      'Lada|112',
      'Lada|1300',
      'Lada|1500',
      'Lada|Desetka',
      'Lada|Aleko',
      'Lada|Granta',
      'Lada|Kalina',
      'Lada|Karavan',
      'Lada|Niva',
      'Lada|Nova',
      'Lada|Samara',
      'Lada|Vesta',
      'Lamborghini|Aventador',
      'Lamborghini|Countach',
      'Lamborghini|Diablo',
      'Lamborghini|Espada',
      'Lamborghini|Gallardo',
      'Lamborghini|Huracan',
      'Lamborghini|Miura',
      'Lamborghini|Murcielago',
      'Lancia|Beta',
      'Lancia|Dedra',
      'Lancia|Delta',
      'Lancia|Flavia',
      'Lancia|Fulvia',
      'Lancia|Kappa',
      'Lancia|Lybra',
      'Lancia|Musa',
      'Lancia|Phedra',
      'Lancia|Prisma',
      'Lancia|Stratos',
      'Lancia|Thema',
      'Lancia|Thesis',
      'Lancia|Voyager',
      'Lancia|Y',
      'Lancia|Ypsilon',
      'Lancia|Zeta',
      'LandRover|Defender',
      'LandRover|Discovery',
      'LandRover|Discovery Sport',
      'LandRover|Freelander',
      'LandRover|Range Rover',
      'LandRover|Range Rover Sport',
      'LandRover|Range Rover Evoque',
      'Lexus|CT',
      'Lexus|GS',
      'Lexus|GX',
      'Lexus|IS',
      'Lexus|LC',
      'Lexus|LFA',
      'Lexus|LS',
      'Lexus|LX',
      'Lexus|NX',
      'Lexus|RC',
      'Lexus|RX',
      'Lexus|SC',
      'London Taxi|FX series',
      'London Taxi|Fairway series',
      'London Taxi|TX series',
      'Lotus|3-Eleven',
      'Lotus|340R',
      'Lotus|Elan',
      'Lotus|Elise',
      'Lotus|Esprit',
      'Lotus|Europa',
      'Lotus|Evora',
      'Lotus|Excel',
      'Lotus|Exige',
      'Lotus|Super seven',
      'Maserati|222',
      'Maserati|224',
      'Maserati|228',
      'Maserati|418',
      'Maserati|420',
      'Maserati|422',
      'Maserati|424',
      'Maserati|430',
      'Maserati|GT 3200',
      'Maserati|Biturbo',
      'Maserati|Coupe',
      'Maserati|Ghibli',
      'Maserati|GranSport',
      'Maserati|GranTurismo',
      'Maserati|GranCabrio',
      'Maserati|Levante',
      'Maserati|Quattroporte',
      'Maserati|Shamal',
      'Maserati|Spyder',
      'Maybach|57',
      'Maybach|62',
      'Maybach|Guard',
      'Maybach|Landaulet',
      'Mazda|121',
      'Mazda|323',
      'Mazda|626',
      'Mazda|929',
      'Mazda|BT-50',
      'Mazda|CX-3',
      'Mazda|CX-5',
      'Mazda|CX-7',
      'Mazda|CX-9',
      'Mazda|Demio',
      'Mazda|Mazda2',
      'Mazda|Mazda3',
      'Mazda|Mazda5',
      'Mazda|Mazda6',
      'Mazda|MPV',
      'Mazda|MX-3',
      'Mazda|MX-5',
      'Mazda|MX-6',
      'Mazda|Premacy',
      'Mazda|RX-7',
      'Mazda|RX-8',
      'Mazda|Tribute',
      'Mazda|Xedos 6',
      'Mazda|Xedos 9',
      'Mercedes-Benz|190',
      'Mercedes-Benz|W123',
      'Mercedes-Benz|AMG GT',
      'Mercedes-Benz|A-Razred',
      'Mercedes-Benz|B-Razred',
      'Mercedes-Benz|C-Razred',
      'Mercedes-Benz|CL-Razred',
      'Mercedes-Benz|CLA-Razred',
      'Mercedes-Benz|CLC-Razred',
      'Mercedes-Benz|CLK-Razred',
      'Mercedes-Benz|CLS-Razred',
      'Mercedes-Benz|E-Razred',
      'Mercedes-Benz|G-Razred',
      'Mercedes-Benz|GL-Razred',
      'Mercedes-Benz|GLA-Razred',
      'Mercedes-Benz|GLC-Razred',
      'Mercedes-Benz|GLC coupe',
      'Mercedes-Benz|GLE-Razred',
      'Mercedes-Benz|GLE coupe',
      'Mercedes-Benz|GLK-Razred',
      'Mercedes-Benz|GLS-Razred',
      'Mercedes-Benz|ML-Razred',
      'Mercedes-Benz|R-Razred',
      'Mercedes-Benz|S-Razred',
      'Mercedes-Benz|SL-Razred',
      'Mercedes-Benz|SLC-Razred',
      'Mercedes-Benz|SLS-Razred',
      'Mercedes-Benz|SLK-Razred',
      'Mercedes-Benz|SLR-Razred',
      'Mercedes-Benz|V-Razred',
      'Mercedes-Benz|Vaneo',
      'Mercedes-Benz|Viano',
      'Mercedes-Benz|Vito',
      'MG|F',
      'MG|GS',
      'MG|MG3',
      'MG|TF',
      'MG|ZR',
      'Mini|-',
      'Mini|Cabrio',
      'Mini|Clubman',
      'Mini|Countryman',
      'Mini|Coupe',
      'Mini|Paceman',
      'Mini|Roadster',
      'Mitsubishi|3000 GT',
      'Mitsubishi|ASX',
      'Mitsubishi|Carisma',
      'Mitsubishi|Colt',
      'Mitsubishi|Diamante',
      'Mitsubishi|Eclipse',
      'Mitsubishi|Galant',
      'Mitsubishi|Grandis',
      'Mitsubishi|i-MiEV',
      'Mitsubishi|L 200',
      'Mitsubishi|L 300',
      'Mitsubishi|Lancer',
      'Mitsubishi|Outlander',
      'Mitsubishi|Pajero',
      'Mitsubishi|Sigma',
      'Mitsubishi|Space Gear',
      'Mitsubishi|Space Runner',
      'Mitsubishi|Space Star',
      'Mitsubishi|Space Wagon',
      'Mitsubishi|Starion',
      'Nissan|100 NX',
      'Nissan|200 SX',
      'Nissan|280 ZX',
      'Nissan|300 ZX',
      'Nissan|350 Z',
      'Nissan|370 Z',
      'Nissan|Almera',
      'Nissan|Almera Tino',
      'Nissan|Altima',
      'Nissan|Bluebird',
      'Nissan|Cherry',
      'Nissan|Cube',
      'Nissan|Evalia',
      'Nissan|GT-R',
      'Nissan|Juke',
      'Nissan|King Cab',
      'Nissan|Leaf',
      'Nissan|Maxima',
      'Nissan|Micra',
      'Nissan|Murano',
      'Nissan|Navara',
      'Nissan|Note',
      'Nissan|NV200',
      'Nissan|Pathfinder',
      'Nissan|Patrol',
      'Nissan|Pick Up',
      'Nissan|Pixo',
      'Nissan|Prairie',
      'Nissan|Primera',
      'Nissan|Pulsar',
      'Nissan|Qashqai',
      'Nissan|Quest',
      'Nissan|Serena',
      'Nissan|Silvia',
      'Nissan|Skyline',
      'Nissan|Sunny',
      'Nissan|Terrano',
      'Nissan|Tiida',
      'Nissan|Vanette',
      'Nissan|X-Trail',
      'NSU|Prinz',
      'NSU|RO-80',
      'Opel|Adam',
      'Opel|Agila',
      'Opel|Ampera',
      'Opel|Antara',
      'Opel|Ascona',
      'Opel|Astra',
      'Opel|Calibra',
      'Opel|Campo',
      'Opel|Cascada',
      'Opel|Combo',
      'Opel|Commodore',
      'Opel|Corsa',
      'Opel|Crossland X',
      'Opel|Diplomat',
      'Opel|Frontera',
      'Opel|GT',
      'Opel|Insignia',
      'Opel|Kadett',
      'Opel|Karl',
      'Opel|Manta',
      'Opel|Meriva',
      'Opel|Mokka',
      'Opel|Monterey',
      'Opel|Monza',
      'Opel|Olympia',
      'Opel|Omega',
      'Opel|Rekord',
      'Opel|Senator',
      'Opel|Signum',
      'Opel|Sintra',
      'Opel|Speedster',
      'Opel|Tigra',
      'Opel|Vectra',
      'Opel|Zafira',
      'Peugeot|104',
      'Peugeot|106',
      'Peugeot|107',
      'Peugeot|108',
      'Peugeot|1007',
      'Peugeot|204',
      'Peugeot|205',
      'Peugeot|206',
      'Peugeot|207',
      'Peugeot|208',
      'Peugeot|2008',
      'Peugeot|301',
      'Peugeot|304',
      'Peugeot|305',
      'Peugeot|306',
      'Peugeot|307',
      'Peugeot|308',
      'Peugeot|309',
      'Peugeot|3008',
      'Peugeot|404',
      'Peugeot|405',
      'Peugeot|406',
      'Peugeot|407',
      'Peugeot|4007',
      'Peugeot|4008',
      'Peugeot|504',
      'Peugeot|505',
      'Peugeot|508',
      'Peugeot|5008',
      'Peugeot|604',
      'Peugeot|605',
      'Peugeot|607',
      'Peugeot|806',
      'Peugeot|807',
      'Peugeot|Bipper',
      'Peugeot|Expert',
      'Peugeot|iOn',
      'Peugeot|Partner',
      'Peugeot|RCZ',
      'Peugeot|Traveller',
      'Piaggio|Porter Van',
      'Pontiac|Bonneville',
      'Pontiac|Fiero',
      'Pontiac|Firebird',
      'Pontiac|Trans Am',
      'Pontiac|Grand Am',
      'Pontiac|Grand Prix',
      'Pontiac|Trans Sport',
      'Porsche|356',
      'Porsche|718',
      'Porsche|911',
      'Porsche|912',
      'Porsche|914',
      'Porsche|924',
      'Porsche|928',
      'Porsche|944',
      'Porsche|959',
      'Porsche|968',
      'Porsche|Boxster',
      'Porsche|Cayenne',
      'Porsche|Cayman',
      'Porsche|Carrera GT',
      'Porsche|Macan',
      'Porsche|Panamera',
      'Proton|serija 300:',
      'Proton|serija 400:',
      'Proton|Persona',
      'Puch|G',
      'Renault|R 4',
      'Renault|R 5',
      'Renault|R 8',
      'Renault|R 9',
      'Renault|R 10',
      'Renault|R 11',
      'Renault|R 12',
      'Renault|R 14',
      'Renault|R 16',
      'Renault|R 18',
      'Renault|R 19',
      'Renault|R 20',
      'Renault|R 21',
      'Renault|R 25',
      'Renault|R 30',
      'Renault|Alaskan',
      'Renault|Alpine',
      'Renault|Avantime',
      'Renault|Captur',
      'Renault|Clio',
      'Renault|Espace',
      'Renault| Grand Espace',
      'Renault|Fluence',
      'Renault|Fuego',
      'Renault|Kadjar',
      'Renault|Kangoo',
      'Renault|Koleos',
      'Renault|Laguna',
      'Renault|Latitude',
      'Renault|Megane',
      'Renault|Modus',
      'Renault| Grand Modus',
      'Renault|Safrane',
      'Renault|Scenic',
      'Renault| Grand Scenic',
      'Renault|Sport Spider',
      'Renault|Talisman',
      'Renault|Thalia',
      'Renault|Twingo',
      'Renault|Twizy',
      'Renault|Vel Satis',
      'Renault|Wind',
      'Renault|Zoe',
      'Rolls-Royce|Corniche',
      'Rolls-Royce|Flying Spur',
      'Rolls-Royce|Ghost',
      'Rolls-Royce|Park Ward',
      'Rolls-Royce|Phantom',
      'Rolls-Royce|Silver Cloud',
      'Rolls-Royce|Silver Dawn',
      'Rolls-Royce|Silver Seraph',
      'Rolls-Royce|Silver Shadow',
      'Rolls-Royce|Silver Spirit',
      'Rolls-Royce|Silver Spur',
      'Rolls-Royce|Wraith',
      'Rover|25',
      'Rover|45',
      'Rover|75',
      'Rover|serija 100:',
      'Rover|serija 200:',
      'Rover|serija 400:',
      'Rover|serija 600:',
      'Rover|serija 800:',
      'Rover|City Rover',
      'Rover|Metro',
      'Rover|Montego',
      'Rover|Streetwise',
      'Saab|9-3',
      'Saab|9-4x',
      'Saab|9-5',
      'Saab|9-7x',
      'Saab|90',
      'Saab|96',
      'Saab|99',
      'Saab|900',
      'Saab|9000',
      'SEAT|Alhambra',
      'SEAT|Altea',
      'SEAT|Arosa',
      'SEAT|Ateca',
      'SEAT|Cordoba',
      'SEAT|Exeo',
      'SEAT|Ibiza',
      'SEAT|Inca',
      'SEAT|Leon',
      'SEAT|Marbella',
      'SEAT|Malaga',
      'SEAT|Mii',
      'SEAT|Toledo',
      'Shunaghuan|Ceo',
      'Škoda|S 105',
      'Škoda|S 120',
      'Škoda|Citigo',
      'Škoda|Fabia',
      'Škoda|Favorit',
      'Škoda|Felicia',
      'Škoda|Forman',
      'Škoda|Kodiaq',
      'Škoda|Octavia',
      'Škoda|Rapid',
      'Škoda|Roomster',
      'Škoda|Superb',
      'Škoda|Yeti',
      'Smart|city cabrio',
      'Smart|city coupe',
      'Smart|crossblade',
      'Smart|forfour',
      'Smart|fortwo',
      'Smart|roadster',
      'Spyker|C8',
      'SsangYong|Actyon',
      'SsangYong|Korando',
      'SsangYong|Kyron',
      'SsangYong|Musso',
      'SsangYong|Rexton',
      'SsangYong|Rodius',
      'SsangYong|Tivoli',
      'Subaru|700 SDX',
      'Subaru|Baja',
      'Subaru|BRZ',
      'Subaru|Forester',
      'Subaru|Impreza',
      'Subaru|Justy',
      'Subaru|Legacy',
      'Subaru|Leone',
      'Subaru|Levorg',
      'Subaru|Libero',
      'Subaru|Outback',
      'Subaru|SVX',
      'Subaru|Trezia',
      'Subaru|Tribeca',
      'Subaru|Vivio',
      'Subaru|WRX STI',
      'Subaru|XT',
      'Subaru|XV',
      'Suzuki|Alto',
      'Suzuki|Baleno',
      'Suzuki|Capuccino',
      'Suzuki|Celerio',
      'Suzuki|Ignis',
      'Suzuki|Jimny',
      'Suzuki|Kizashi',
      'Suzuki|Liana',
      'Suzuki|Maruti',
      'Suzuki|Samurai',
      'Suzuki|Splash',
      'Suzuki|Swift',
      'Suzuki|SX4',
      'Suzuki|SX4 S-Cross',
      'Suzuki|Vitara',
      'Suzuki|Grand Vitara',
      'Suzuki|Wagon R',
      'Suzuki|X-90',
      'Talbot|Horizon',
      'Talbot|Samba',
      'Talbot|Solara',
      'Tata|Nano',
      'Tata|Indica',
      'Tata|Indigo',
      'Tata|Xenon',
      'Tata|Safari',
      'Tazzari|Zero',
      'Tesla Motors|Roadster',
      'Tesla Motors|Model 3',
      'Tesla Motors|Model S',
      'Tesla Motors|Model X',
      'Toyota|4-Runner',
      'Toyota|Auris',
      'Toyota|Avensis',
      'Toyota|Avensis Verso',
      'Toyota|Aygo',
      'Toyota|C-HR',
      'Toyota|Camry',
      'Toyota|Carina',
      'Toyota|Celica',
      'Toyota|Corolla',
      'Toyota|Corolla Verso',
      'Toyota|FJ',
      'Toyota|GT 86',
      'Toyota|Hi-Lux',
      'Toyota|HiAce',
      'Toyota|IQ',
      'Toyota|Land Cruiser',
      'Toyota|Mirai',
      'Toyota|MR-2',
      'Toyota|LiteAce',
      'Toyota|Paseo',
      'Toyota|Picnic',
      'Toyota|Previa',
      'Toyota|Prius',
      'Toyota|Proace',
      'Toyota|RAV4',
      'Toyota|Starlet',
      'Toyota|Supra',
      'Toyota|Tercel',
      'Toyota|Urban Cruiser',
      'Toyota|Verso',
      'Toyota|Verso S',
      'Toyota|Yaris',
      'Toyota|Yaris Verso',
      'Trabant|601',
      'Trabant|Cabrio',
      'Triumph|Dolomite',
      'Triumph|Moss',
      'Triumph|Spitfire',
      'Triumph|TR3',
      'Triumph|TR4',
      'Triumph|TR5',
      'Triumph|TR6',
      'Triumph|TR7',
      'Triumph|TR8',
      'Volvo|240',
      'Volvo|340',
      'Volvo|360',
      'Volvo|440',
      'Volvo|460',
      'Volvo|480',
      'Volvo|740',
      'Volvo|760',
      'Volvo|780',
      'Volvo|850',
      'Volvo|940',
      'Volvo|960',
      'Volvo|C30',
      'Volvo|C70',
      'Volvo|S40',
      'Volvo|S60',
      'Volvo|S70',
      'Volvo|S80',
      'Volvo|S90',
      'Volvo|V40',
      'Volvo|V50',
      'Volvo|V60',
      'Volvo|V70',
      'Volvo|V90',
      'Volvo|XC60',
      'Volvo|XC70',
      'Volvo|XC90',
      'Volkswagen|Amarok',
      'Volkswagen|Beetle',
      'Volkswagen|Bora',
      'Volkswagen|Buggy',
      'Volkswagen|Caddy',
      'Volkswagen|California',
      'Volkswagen|Caravelle',
      'Volkswagen|CC',
      'Volkswagen|Corrado',
      'Volkswagen|Derby',
      'Volkswagen|Eos',
      'Volkswagen|Fox',
      'Volkswagen|Golf',
      'Volkswagen|Golf Plus',
      'Volkswagen|Golf Sportsvan',
      'Volkswagen|CrossGolf',
      'Volkswagen|Hrošč',
      'Volkswagen|Jetta',
      'Volkswagen|Karmann Ghia',
      'Volkswagen|Lupo',
      'Volkswagen|Multivan',
      'Volkswagen|Passat',
      'Volkswagen|Passat CC',
      'Volkswagen|Phaeton',
      'Volkswagen|Polo',
      'Volkswagen|CrossPolo',
      'Volkswagen|Santana',
      'Volkswagen|Scirocco',
      'Volkswagen|Sharan',
      'Volkswagen|Shuttle',
      'Volkswagen|Taro',
      'Volkswagen|Tiguan',
      'Volkswagen|Tiguan Allspace',
      'Volkswagen|Touareg',
      'Volkswagen|Touran',
      'Volkswagen|CrossTouran',
      'Volkswagen|Transporter',
      'Volkswagen|up!',
      'Volkswagen|Vento',
      'Volkswagen|XL1',
      'Zastava|101',
      'Zastava|128',
      'Zastava|750',
      'Zastava|850',
      'Zastava|1300',
      'Zastava|1500',
      'Zastava|Buggy',
      'Zastava|Yugo',
      'Zastava|Yugo Florida'
    ];

    $picked = explode('|', $brandsAndModels[array_rand($brandsAndModels, 1)]);

    return [
        'brand'         => $picked[0],
        'model'         => $picked[1],
        'user_id'       => $faker->numberBetween(1, 10),
        'type'          => ['coupe', 'convertable', 'suv', 'sedan'][$faker->numberBetween(0, 3)]
    ];
});
